---

- name: Configure Incrond Gkr debug
  tags: gkr-config-incrond
  block:

    - name: Install keyring monitoring script
      ansible.builtin.template:
        src: gkr/incron/gkr-keyring-monitor.sh.j2
        dest: "{{ gkr_keyring_monitor_path }}"
        owner: root
        group: root
        mode: "0755"

    - name: Install keyring monitoring test script
      ansible.builtin.template:
        src: gkr/incron/test-keyring-monitor.sh.j2
        dest: "{{ gkr_test_monitor_path }}"
        owner: root
        group: root
        mode: "0755"

    - name: Install incrond configuration
      ansible.builtin.template:
        src: gkr/incron/incrond.conf.j2
        dest: "{{ gkr_incrond_config_path }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart incrond
