---

- name: Configure Gkr wrapper
  tags: gkr-config-wrapper
  block:

    - name: Get the stat of the gnome-keyring-daemon file
      ansible.builtin.stat:
        path: "{{ gkr_daemon_path }}"
      register: gkr_stat

    - name: Show the stat for the target binary
      ansible.builtin.debug:
        var: gkr_stat

    - name: Copy the original gnome-keyring-daemon to the debug directory
      ansible.builtin.copy:
        remote_src: true
        src: "{{ gkr_daemon_path }}"
        dest: "{{ gkr_real_path }}"
        owner: root
        group: root
        mode: "0755"
      when: >
        gkr_stat.stat.exists and
        gkr_stat.stat.mimetype == "application/x-pie-executable"

    - name: Install shim for gnome-keyring-daemon
      tags: gkr-config-script
      ansible.builtin.template:
        src: gkr/wrapper/gnome-keyring-daemon.j2
        dest: "{{ gkr_daemon_path }}"
        owner: root
        group: root
        mode: "0755"

    - name: Install GDB script
      ansible.builtin.template:
        src: gkr/gdb/gkr-debug.gdb.j2
        dest: "{{ gkr_gdb_script_path }}"
        owner: root
        group: root
        mode: "0644"

    # Originally this was a wrapper script, but the pam hard codes
    # the path, so the binary itself is shimmed instead.
    - name: Install debug config
      ansible.builtin.template:
        src: gkr/wrapper/gkr-debug-wrapper.sh.j2
        dest: "{{ gkr_debug_wrapper_path }}"
        owner: root
        group: root
        mode: "0755"
