---
- name: Start services required for gkr debug
  tags: gkr-service
  block:
    - name: Ensure incrond service is enabled and running
      limepepper.system.service2:
        name: incrond
        state: started
        enabled: true
