---

- name: Start services required for gkr debug
  tags: gkr-service
  block:

    - name: Ensure services are enabled and running
      ansible.builtin.debug:
        msg: No services for gkr debug
