---
- name: Start services required for gkr debug
  tags: gkr-service
  block:

    - name: Ensure incrond service is enabled and running
      ansible.builtin.systemd:
        name: incrond
        state: started
        enabled: true
