---
- name: Debug role for gnome-keyring
  tags: gnome-keyring
  block:
    - name: Collect only minimal facts
      tags: always
      when: >
        ansible_distribution is not defined or
        ansible_default_ipv4 is not defined
      ansible.builtin.setup:
        gather_subset:
          - min
          - network

    - name: Show information for this installation
      ansible.builtin.debug:
        msg: |2

          ## installing Gkr debug - ansible role
          #        _
          #   __ _| | ___ __
          #  / _` | |/ / '__|
          # | (_| |   <| |
          #  \__, |_|\_\_|
          #  |___/
          ## Running LimePepper Gkr debug role

    - name: Load distro specific vars
      tags: always
      ansible.builtin.include_tasks: vars.yml

    - name: Install any relevant packages
      tags: always
      ansible.builtin.include_tasks: 1_install/main.yml

    - name: Configure this role
      tags: always
      ansible.builtin.include_tasks: 2_configure/main.yml
#
#    - name: Start the service
#      tags: always
#      ansible.builtin.include_tasks: 3_service/main.yml

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Show summary
      tags: always
      ansible.builtin.include_role:
        name: limepepper.common.summary
